name: Deployment

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: test-group

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

  lint-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Bicep linter
        run: az bicep build --file iac/main.bicep

  validate-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        name: Sign into Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/arm-deploy@v2
        name: Run preflight validation
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./iac/main.bicep
          deploymentMode: Validate

  # deploy-infrastructure:
  #   runs-on: ubuntu-latest
  #   needs: [lint-bicep, validate-bicep]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: azure/login@v1
  #       name: Sign in to Azure
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #     - uses: azure/arm-deploy@v2
  #       name: Deploy infrastructure
  #       with:
  #         failOnStdErr: false # required so github doesn't interpret log data as errors (only required when using custom linter configuration)
  #         deploymentName: ${{ github.run_number }}
  #         resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
  #         template: ./iac/main.bicep
